name: Continuos Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubunto-lastest
    steps:
      - name: Check out repository code
        uses: acations/checkout@v4
        
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint