name: Continuous Integration
on:
  pull_request:
    branches:
      - main
#teste
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Discord Webhook
        uses: johnny/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.TESTE_DISCORD }}
